/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ca.ulaval.glo2004.visualizer;

import java.awt.Container;
import java.awt.Graphics;
import java.awt.Graphics2D;

/**
 *
 * @author raphael
 */
public class visualizerScale extends javax.swing.JPanel {

    private Visualizer parent = null;
    private int measurement = 12;
    
    /**
     * Creates new form visualizerScale
     */
    public visualizerScale() {
        initComponents();
    }
    
    
    protected void paintComponent(Graphics g) {
        if(this.parent == null){
            return;
        }
        this.parent = (Visualizer) this.getParent();
        
        super.paintComponent(g);
        Graphics2D g2 = (Graphics2D) g.create();
        
        int y = this.getHeight() / 2;
        int x1 = 10;
        int yTop = 10;
        int height = this.getHeight() - (yTop * 2);
        int length;
        boolean isOk = false;
        do{
            //length = this.parent.InchesToPixels(measurement);
            length = 0;
            if(length < 40){
                this.setMeasurement(measurement + 12);
            }else if(length > 80){
                if(measurement > 12){
                    this.setMeasurement(measurement - 12);
                }else{
                    this.setMeasurement(measurement - 1);
                }
            }else{
                isOk = true;
            }
        }while(!isOk);
        
        g2.drawLine(x1, y , x1 + length, (int) y);
        g2.drawLine(x1 + length, yTop, x1 + length, yTop+height);
        g2.drawLine(x1, yTop, x1, yTop+height);
        String str = this.getMeasurement()+"\"";
        g2.drawString(str, x1 + (length / 2) - 10, y + 12);
    }
    
    private int getMeasurement() {
        return measurement;
    }

    private void setMeasurement(int measurement) {
        this.measurement = measurement;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
