/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ca.ulaval.glo2004.gui;

import ca.ulaval.glo2004.cabanon.domaine.Controlleur;
import ca.ulaval.glo2004.cabanon.domaine.murs.Mur;
import java.util.UUID;

/**
 *
 * @author raphael
 */
import ca.ulaval.glo2004.visualizer.Visualizer;
import java.awt.event.ActionEvent;

public abstract class AddedAccessoryPane extends javax.swing.JPanel {

    private int index;
    protected MainWindow parent;
    protected Controlleur controlleur;
    protected UUID id;
    protected Mur.orientations orientation;
    protected Visualizer visualizer;
    /**
     * Creates new form AddedWindowPane
     */
    public AddedAccessoryPane(String accessoire, MainWindow parent){
        initComponents();
        this.init(index,  accessoire,  parent);
        this.visualizer = parent.getVisualizer();
    }

    public AddedAccessoryPane(UUID id, String accessoire, MainWindow parent) {
        initComponents();
        this.init(index,  accessoire,  parent);
        this.id = id;
        this.visualizer = parent.getVisualizer();
    }

    private void init(int index, String accessoire, MainWindow parent){
        //this.count.setVisible(false);
        this.index = index;
        this.accessoryName.setText(accessoire);
        this.parent = parent;
        this.controlleur = parent.getControlleur();
    }

    public void setId(UUID id){
        this.id = id;
    }
    
    public UUID getID(){
        return this.id;
    }

    public void setOrientation(Mur.orientations orientation){
        this.orientation = orientation;
    }

    public Mur.orientations getOrientation(){
        return this.orientation;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        size = new javax.swing.JPanel();
        largeur = new javax.swing.JTextField();
        hauteur = new javax.swing.JTextField();
        Ok = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        position = new javax.swing.JPanel();
        XWrapper = new javax.swing.JPanel();
        PosX = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        YWrapper = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        PosY = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        DistanceMontant = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        distanceMontant = new javax.swing.JTextField();
        OkMontant = new javax.swing.JButton();
        taillLinteau = new javax.swing.JPanel();
        LinteauWrapper = new javax.swing.JPanel();
        LinteauComboBox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        accessoryName = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        setMaximumSize(new java.awt.Dimension(280, 300));
        setMinimumSize(new java.awt.Dimension(280, 300));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(242, 300));

        largeur.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        largeur.setText("0");

        hauteur.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        hauteur.setText("0");

        Ok.setText("Ok");

        jLabel5.setText("Largeur:");

        jLabel6.setText("Hauteur:");

        javax.swing.GroupLayout sizeLayout = new javax.swing.GroupLayout(size);
        size.setLayout(sizeLayout);
        sizeLayout.setHorizontalGroup(
            sizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sizeLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(sizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sizeLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6))
                    .addGroup(sizeLayout.createSequentialGroup()
                        .addComponent(largeur, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hauteur, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Ok)))
                .addContainerGap())
        );
        sizeLayout.setVerticalGroup(
            sizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sizeLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(sizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(7, 7, 7)
                .addGroup(sizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(largeur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(sizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(hauteur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Ok)))
                .addGap(1, 1, 1))
        );

        position.setLayout(new javax.swing.BoxLayout(position, javax.swing.BoxLayout.LINE_AXIS));

        PosX.setMaximumSize(new java.awt.Dimension(60, 22));
        PosX.setMinimumSize(new java.awt.Dimension(60, 22));
        PosX.setPreferredSize(new java.awt.Dimension(60, 22));

        jLabel3.setText("X");

        javax.swing.GroupLayout XWrapperLayout = new javax.swing.GroupLayout(XWrapper);
        XWrapper.setLayout(XWrapperLayout);
        XWrapperLayout.setHorizontalGroup(
            XWrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(XWrapperLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PosX, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        XWrapperLayout.setVerticalGroup(
            XWrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(XWrapperLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(XWrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PosX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap())
        );

        position.add(XWrapper);

        jLabel7.setText("  Y");

        PosY.setMaximumSize(new java.awt.Dimension(60, 22));
        PosY.setMinimumSize(new java.awt.Dimension(60, 22));
        PosY.setPreferredSize(new java.awt.Dimension(60, 22));

        javax.swing.GroupLayout YWrapperLayout = new javax.swing.GroupLayout(YWrapper);
        YWrapper.setLayout(YWrapperLayout);
        YWrapperLayout.setHorizontalGroup(
            YWrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(YWrapperLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PosY, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );
        YWrapperLayout.setVerticalGroup(
            YWrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(YWrapperLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(YWrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PosY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap())
        );

        position.add(YWrapper);

        jLabel2.setText("Position");

        jLabel1.setText("Distance entre montant");

        distanceMontant.setText("0");

        OkMontant.setText("Ok");

        javax.swing.GroupLayout DistanceMontantLayout = new javax.swing.GroupLayout(DistanceMontant);
        DistanceMontant.setLayout(DistanceMontantLayout);
        DistanceMontantLayout.setHorizontalGroup(
            DistanceMontantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DistanceMontantLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(distanceMontant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(OkMontant)
                .addGap(0, 18, Short.MAX_VALUE))
        );
        DistanceMontantLayout.setVerticalGroup(
            DistanceMontantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DistanceMontantLayout.createSequentialGroup()
                .addGroup(DistanceMontantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(distanceMontant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OkMontant))
                .addGap(0, 9, Short.MAX_VALUE))
        );

        LinteauComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2x6", "2x8", "2x10", " " }));

        jLabel4.setText("Linteau:");

        javax.swing.GroupLayout LinteauWrapperLayout = new javax.swing.GroupLayout(LinteauWrapper);
        LinteauWrapper.setLayout(LinteauWrapperLayout);
        LinteauWrapperLayout.setHorizontalGroup(
            LinteauWrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LinteauWrapperLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LinteauWrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(LinteauComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        LinteauWrapperLayout.setVerticalGroup(
            LinteauWrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LinteauWrapperLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LinteauComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout taillLinteauLayout = new javax.swing.GroupLayout(taillLinteau);
        taillLinteau.setLayout(taillLinteauLayout);
        taillLinteauLayout.setHorizontalGroup(
            taillLinteauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(taillLinteauLayout.createSequentialGroup()
                .addComponent(LinteauWrapper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 34, Short.MAX_VALUE))
        );
        taillLinteauLayout.setVerticalGroup(
            taillLinteauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(taillLinteauLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LinteauWrapper, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        accessoryName.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        accessoryName.setText("Placeholder");

        jButton1.setText("Supprimer");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(accessoryName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(accessoryName)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(234, 234, 234))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DistanceMontant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(position, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(size, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(taillLinteau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(taillLinteau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(size, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(7, 7, 7)
                .addComponent(position, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DistanceMontant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(155, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
       // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

  public void hauteurActionPerformed(ActionEvent evt){}

  public abstract void updateValues();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JPanel DistanceMontant;
    protected javax.swing.JComboBox<String> LinteauComboBox;
    protected javax.swing.JPanel LinteauWrapper;
    protected javax.swing.JButton Ok;
    protected javax.swing.JButton OkMontant;
    protected javax.swing.JSpinner PosX;
    protected javax.swing.JSpinner PosY;
    protected javax.swing.JPanel XWrapper;
    protected javax.swing.JPanel YWrapper;
    private javax.swing.JLabel accessoryName;
    protected javax.swing.JTextField distanceMontant;
    protected javax.swing.JTextField hauteur;
    protected javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    protected javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    protected javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    protected javax.swing.JTextField largeur;
    protected javax.swing.JPanel position;
    protected javax.swing.JPanel size;
    protected javax.swing.JPanel taillLinteau;
    // End of variables declaration//GEN-END:variables
}
