/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ca.ulaval.glo2004.gui;

import ca.ulaval.glo2004.cabanon.domaine.Controlleur;
import ca.ulaval.glo2004.preferences.Preferences;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JFileChooser;
import static resources.UnitConverter.fractionator;

import static resources.UnitConverter.toMoneyString;
import static resources.UnitConverter.toMoneyDouble;

/**
 *
 * @author raphael
 */
public class CostPane extends javax.swing.JFrame {
    
    private final Controlleur controlleur;
    private final MainWindow mainWindow;

    /**
     * Creates new form PreferencePane
     * @param controlleur
     * @param mainWindow
     */
    public CostPane(Controlleur controlleur, MainWindow mainWindow) {
        this.controlleur = controlleur;
        this.mainWindow = mainWindow;
        initComponents();
        this.textPanelPrixTotal.setText(mainWindow.champPrixMainWindow.getText());
        textFieldPrixPied24.setText(toMoneyString(Preferences.getPrixPied24()));
        textFieldPrixPied26.setText(toMoneyString(Preferences.getPrixPied26()));
        textFieldPrixPied28.setText(toMoneyString(Preferences.getPrixPied28()));
        textFieldPrixPied210.setText(toMoneyString(Preferences.getPrixPied210()));
    }
    
    public static void saveToCsv(ArrayList<double[]> uncombinedArrayList) {
        ArrayList<double[]> arrayList = combineArrays(uncombinedArrayList);
        // Choose a file location using file explorer
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Sauvegarder fichier CSV");
        int userSelection = fileChooser.showSaveDialog(null);
        if (userSelection == JFileChooser.APPROVE_OPTION) {
            File fileToSave = fileChooser.getSelectedFile();

            String fileName = fileToSave.getAbsolutePath();
            if(!fileName.endsWith(".csv")){
                fileName = fileName+".csv";
            }

            // Write the ArrayList of arrays to a CSV file
            try (FileWriter writer = new FileWriter(fileName)) {
                // Write header row
                writer.write("Dimension,Length,Left Cut,Right Cut,Quantity\n");
                
                DecimalFormat df = new DecimalFormat("#.##");
                
                // Write data rows
                for (double[] array : arrayList) {
                    if (array[4] != 0){
                        StringBuilder sb = new StringBuilder();
                        String typeBois = String.valueOf((int) array[0]).substring(0, 1) + "x" + String.valueOf((int) array[0]).substring(1);
                        sb.append(typeBois).append(",");
                        sb.append(fractionator(array[1])).append(",");
                        sb.append(df.format(array[2])).append(",");
                        sb.append(df.format(array[3])).append(",");
                        sb.append((int) array[4]).append("\n");
                        writer.write(sb.toString());
                    }
                }
            } catch (IOException e) {
                System.err.format("IOException: %s%n", e);
            }
        }
    }
    
    
    //Cette fonction utilitaire a été produite par ChatGPT
    public static ArrayList<double[]> combineArrays(ArrayList<double[]> arrayOfArrays) {
        HashMap<String, Double> map = new HashMap<>();
        for (double[] subArray : arrayOfArrays) {
            String key = subArray[0] + "," + subArray[1] + "," + subArray[2] + "," + subArray[3];
            if (map.containsKey(key)) {
                double sum = map.get(key) + subArray[4];
                map.put(key, sum);
            } else {
                map.put(key, subArray[4]);
            }
        }

        ArrayList<double[]> combinedArray = new ArrayList<>();
        for (String key : map.keySet()) {
            double[] combinedSubArray = new double[5];
            String[] keyParts = key.split(",");
            for (int i = 0; i < keyParts.length; i++) {
                combinedSubArray[i] = Double.parseDouble(keyParts[i]);
            }
            combinedSubArray[4] = map.get(key);
            combinedArray.add(combinedSubArray);
        }
        return combinedArray;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelFrameCout = new javax.swing.JLabel();
        panelPrixTotal = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textPanelPrixTotal = new javax.swing.JTextPane();
        jLabel5 = new javax.swing.JLabel();
        panelLongueurParType = new javax.swing.JPanel();
        labelLongueurParType = new javax.swing.JLabel();
        boutonExporterLongueurs = new javax.swing.JButton();
        panelPrixPiedLineaire = new javax.swing.JPanel();
        labelPrixPiedLineaire = new javax.swing.JLabel();
        labelPrix24 = new javax.swing.JLabel();
        labelPrix26 = new javax.swing.JLabel();
        labelPrix28 = new javax.swing.JLabel();
        labelPrix210 = new javax.swing.JLabel();
        textFieldPrixPied24 = new javax.swing.JFormattedTextField();
        textFieldPrixPied26 = new javax.swing.JFormattedTextField();
        textFieldPrixPied28 = new javax.swing.JFormattedTextField();
        textFieldPrixPied210 = new javax.swing.JFormattedTextField();
        boutonOkSetPrixPiedLineaire = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        labelFrameCout.setText("Coût du modèle");

        jLabel7.setText("Coût total de la charpente : ");

        jScrollPane2.setViewportView(textPanelPrixTotal);

        jLabel5.setText("$");

        javax.swing.GroupLayout panelPrixTotalLayout = new javax.swing.GroupLayout(panelPrixTotal);
        panelPrixTotal.setLayout(panelPrixTotalLayout);
        panelPrixTotalLayout.setHorizontalGroup(
            panelPrixTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrixTotalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPrixTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrixTotalLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5))
                    .addComponent(jLabel7))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelPrixTotalLayout.setVerticalGroup(
            panelPrixTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrixTotalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPrixTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        labelLongueurParType.setText("Liste des pièces :");

        boutonExporterLongueurs.setText("Exporter");
        boutonExporterLongueurs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonExporterLongueursActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLongueurParTypeLayout = new javax.swing.GroupLayout(panelLongueurParType);
        panelLongueurParType.setLayout(panelLongueurParTypeLayout);
        panelLongueurParTypeLayout.setHorizontalGroup(
            panelLongueurParTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLongueurParTypeLayout.createSequentialGroup()
                .addComponent(labelLongueurParType)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(boutonExporterLongueurs)
                .addContainerGap())
        );
        panelLongueurParTypeLayout.setVerticalGroup(
            panelLongueurParTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLongueurParTypeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLongueurParTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelLongueurParType)
                    .addComponent(boutonExporterLongueurs))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        labelPrixPiedLineaire.setText("Coût au pied linéaire des planches :");

        labelPrix24.setText("2 x 4 :");

        labelPrix26.setText("2 x 6 :");

        labelPrix28.setText("2 x 8  :");

        labelPrix210.setText("2 x 10 :");

        textFieldPrixPied24.setText("jFormattedTextField1");
        textFieldPrixPied24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldPrixPied24ActionPerformed(evt);
            }
        });

        textFieldPrixPied26.setText("jFormattedTextField2");

        textFieldPrixPied28.setText("jFormattedTextField3");

        textFieldPrixPied210.setText("jFormattedTextField4");
        textFieldPrixPied210.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldPrixPied210ActionPerformed(evt);
            }
        });

        boutonOkSetPrixPiedLineaire.setText("OK");
        boutonOkSetPrixPiedLineaire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonOkSetPrixPiedLineaireActionPerformed(evt);
            }
        });

        jLabel1.setText("$");

        jLabel2.setText("$");

        jLabel3.setText("$");

        jLabel4.setText("$");

        javax.swing.GroupLayout panelPrixPiedLineaireLayout = new javax.swing.GroupLayout(panelPrixPiedLineaire);
        panelPrixPiedLineaire.setLayout(panelPrixPiedLineaireLayout);
        panelPrixPiedLineaireLayout.setHorizontalGroup(
            panelPrixPiedLineaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrixPiedLineaireLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelPrixPiedLineaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrixPiedLineaireLayout.createSequentialGroup()
                        .addComponent(labelPrix24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textFieldPrixPied24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1))
                    .addGroup(panelPrixPiedLineaireLayout.createSequentialGroup()
                        .addComponent(labelPrix26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textFieldPrixPied26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addGroup(panelPrixPiedLineaireLayout.createSequentialGroup()
                        .addGroup(panelPrixPiedLineaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelPrixPiedLineaireLayout.createSequentialGroup()
                                .addComponent(labelPrix210)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textFieldPrixPied210, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelPrixPiedLineaireLayout.createSequentialGroup()
                                .addComponent(labelPrix28)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textFieldPrixPied28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)))
                        .addGap(8, 8, 8)
                        .addComponent(boutonOkSetPrixPiedLineaire, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11))
            .addGroup(panelPrixPiedLineaireLayout.createSequentialGroup()
                .addComponent(labelPrixPiedLineaire)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelPrixPiedLineaireLayout.setVerticalGroup(
            panelPrixPiedLineaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrixPiedLineaireLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelPrixPiedLineaire)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPrixPiedLineaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPrix24)
                    .addComponent(textFieldPrixPied24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPrixPiedLineaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPrix26)
                    .addComponent(textFieldPrixPied26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPrixPiedLineaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPrix28)
                    .addComponent(textFieldPrixPied28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPrixPiedLineaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPrix210)
                    .addComponent(textFieldPrixPied210, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boutonOkSetPrixPiedLineaire)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panelLongueurParType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelPrixPiedLineaire, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelFrameCout)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelPrixTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelFrameCout)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelPrixPiedLineaire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelLongueurParType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelPrixTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boutonExporterLongueursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonExporterLongueursActionPerformed
        saveToCsv(this.controlleur.miseAJourCout());
    }//GEN-LAST:event_boutonExporterLongueursActionPerformed

    private void boutonOkSetPrixPiedLineaireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonOkSetPrixPiedLineaireActionPerformed
        Preferences.setPrixPied24(toMoneyDouble(textFieldPrixPied24.getText()));
        Preferences.setPrixPied26(toMoneyDouble(textFieldPrixPied26.getText()));
        Preferences.setPrixPied28(toMoneyDouble(textFieldPrixPied28.getText()));
        Preferences.setPrixPied210(toMoneyDouble(textFieldPrixPied210.getText()));
        this.mainWindow.miseAJourCout();
        this.textPanelPrixTotal.setText(mainWindow.champPrixMainWindow.getText());
    }//GEN-LAST:event_boutonOkSetPrixPiedLineaireActionPerformed

    private void textFieldPrixPied210ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldPrixPied210ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldPrixPied210ActionPerformed

    private void textFieldPrixPied24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldPrixPied24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldPrixPied24ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CostPane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CostPane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CostPane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CostPane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
               // new CostPane().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boutonExporterLongueurs;
    private javax.swing.JButton boutonOkSetPrixPiedLineaire;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelFrameCout;
    private javax.swing.JLabel labelLongueurParType;
    private javax.swing.JLabel labelPrix210;
    private javax.swing.JLabel labelPrix24;
    private javax.swing.JLabel labelPrix26;
    private javax.swing.JLabel labelPrix28;
    private javax.swing.JLabel labelPrixPiedLineaire;
    private javax.swing.JPanel panelLongueurParType;
    private javax.swing.JPanel panelPrixPiedLineaire;
    private javax.swing.JPanel panelPrixTotal;
    private javax.swing.JFormattedTextField textFieldPrixPied210;
    private javax.swing.JFormattedTextField textFieldPrixPied24;
    private javax.swing.JFormattedTextField textFieldPrixPied26;
    private javax.swing.JFormattedTextField textFieldPrixPied28;
    private javax.swing.JTextPane textPanelPrixTotal;
    // End of variables declaration//GEN-END:variables
}
